### ISSUE TITLE
Fitur Cari berdasarkan

### ISSUE THREAD

**Issue by geetuck** [kholilboy/Aisyah-Bukan-Bot#2]
Bagaimana cara untuk menambahkan command cari berdasarkan ID/Nama MK agar ketika kita klik /cari itu ga muncul semua.

Terima Kasih

**Comment by kholilrnm** [comment]
Terima kasih telah bertanya agan/sis drydiary, untuk command cari berdasarkan id/nama mk caranya sama seperti pada command updateDataCatatan.php pada repo bot ini gan/sis. 

jadi ketika melakukan command misalnya mencari mata kuliah tinggal mengganti parameter query yaitu (select * from ... where id='apa yang dicari tadi berdasarkan id/nama mk');

yang kemudian tinggal di view seperti pada kode file viewDataUser.php

apakah sudah bisa terjawab ?

**Comment by geetuck** [comment]
`<?php 
require_once 'database/configDB.php';


function cariDataValins($id_user, $kode_mk, $nama_mk, $catatan_mk, $deadline_mk){
    // pengecekan data terlebih dahulu sebelum di eksekusi
    $queryFlagUpdate = "SELECT deadline_mk FROM tb_catatan_mk WHERE id_user = $id_user AND id_mk=$deadline_mk";
    $resultQueryFlag  = mysqli_query(connDB(), $queryFlagUpdate); 

    $message = "";

    if ($resultQueryFlag->num_rows > 0) {
        while ($viewDataCatatanUser = mysqli_fetch_assoc($resultQueryFlag)) {
            $resultCatatanUser = (object) $viewDataCatatanUser;
            
            $message .= "ID Data         : " . $resultCatatanUser->id_mk . PHP_EOL;
            $message .= "TANGGAL     : " . $resultCatatanUser->nama_mk . PHP_EOL;
            $message .= "NAMA ODP  : " . $resultCatatanUser->catatan_mk . PHP_EOL;
            $message .= "VALINS ID     : " . $resultCatatanUser->deadline_mk . PHP_EOL;
            $message .= "\n";

        }
    }
    else{
        $message = "Data masih kosong.";
    }

    return $message;
    
}

?>`

Saya merubah queryFlagUpdate dan if itu saya ambil dari viewDataUser.php
Apakah seperti itu?
namun muncul data masih kosong mas

**Comment by kholilrnm** [comment]
Cara melihat error bisa agan lihat pada cmd nya (yang php -S localhost) disana dapat terlihat errornya..

untuk kode agan 
function cariDataValins($id_user, $kode_mk, $nama_mk, $catatan_mk, $deadline_mk){
variabel parameter nama, catatan, deadline tidak perlu.., yang diperlukan cuman id user dan kode mk

untuk query $queryFlagUpdate 
$queryFlagUpdate = "SELECT deadline_mk FROM tb_catatan_mk WHERE id_user = $id_user AND id_mk=$deadline_mk";
diganti menjadi 
$queryFlagUpdate = "SELECT * FROM tb_catatan_mk WHERE id_user = $id_user AND id_mk=$kode_mk";

**Comment by kholilrnm** [comment]
Untuk Lengkap kode seperti ini :
pada file bot,php tambahkan baris kode :


`

$botman->hears("/cari_catatan {kode_mk}", function (Botman $bot, $kode_mk) {
    $user = $bot->getUser();
    $firstname = $user->getFirstName();
    $id_user = $user->getId();

    include "command/requestChat.php";
    
    $kode_mk = $kode_mk;
    
    include "command/cariDataCatatan.php";

    $message = cariDataCatatan($id_user, $kode_mk);
    $bot->reply($message);

});

`

**Comment by kholilrnm** [comment]
Kemudian tambahkan file di folder command-> 'cariDataCatatan.php'
isi kodenya


`<?php 
require_once 'database/configDB.php';


function cariDataCatatan($id_user, $kode_mk){
	// pengecekan data terlebih dahulu sebelum di eksekusi
	$queryCariDataCatatan = "SELECT * FROM tb_catatan_mk WHERE id_user = $id_user AND id_mk=$kode_mk";
	$resultQueryFlag  = mysqli_query(connDB(), $queryCariDataCatatan); 

    $message = "";

    // ketika data ada dan sesuai eksekusi bro
    if ($resultQueryFlag->num_rows > 0) {
        while ($viewDataCatatanUser = mysqli_fetch_assoc($resultQueryFlag)) {
            $resultCatatanUser = (object) $viewDataCatatanUser;
            
            $message .= "ID M.K   : " . $resultCatatanUser->id_mk . PHP_EOL;
            $message .= "Nama M.K   : " . $resultCatatanUser->nama_mk . PHP_EOL;
            $message .= "Catatan M.K   : " . $resultCatatanUser->catatan_mk . PHP_EOL;
            $message .= "Deadline M.K   : " . $resultCatatanUser->deadline_mk . PHP_EOL;
            $message .= "\n";

        }
    }
    else {
        $message = "Data Masih Kosong 🙄";
    }
    
    return $message;
}

?>


`

**Comment by kholilrnm** [comment]
![image](https://user-images.githubusercontent.com/45350583/95869165-4a229280-0d95-11eb-9fcb-746c7823bfe7.png)
