### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by Fayiawaluddinzaki** [kholilboy/Aisyah-Bukan-Bot#3]
berhasil set webhook tetapi error saat melakukan getWebhookinfo pada telegram

error code 404

{
ok: true,
result: {
url: "www.kelompok2api2020.my.id/bot/bot.php",
has_custom_certificate: false,
pending_update_count: 49,
last_error_date: 1603034522,
last_error_message: "Wrong response from the webhook: 404 Not Found",
max_connections: 40
}

**Comment by kholilrnm** [comment]
Maaf baru saya balas, di catatan readme ini saya ndak ada keterangan untuk melakukan getWebhook, untuk error dari getwebhook saya belum tau solusinya, kalau misalkan setWebhook sudah bisa success yang berarti ndak perlu dilakukan getwebhook. kemungkinan last_error_message : error 404 not found yang berarti <b>pesan error terakhir</b> yaitu salah ngewebhook pada alamat yang tidak ada.

getWebhookInfo :
https://api.telegram.org/bot{my_bot_token}/getWebhookInfo

**Comment by kholilrnm** [comment]
![image](https://user-images.githubusercontent.com/45350583/96616905-20391500-132d-11eb-8f9e-ecfc53712ad5.png)
